name: Deploy to GitHub Pagesname: Deploy to GitHub Pages



on:on:

  push:  push:

    branches:    branches:

      - master      - master



permissions:permissions:

  contents: read  contents: read

  pages: write  pages: write

  id-token: write  id-token: write



concurrency:concurrency:

  group: pages  group: pages

  cancel-in-progress: false  cancel-in-progress: false



jobs:jobs:

  build:  build:

    runs-on: ubuntu-latest    runs-on: ubuntu-latest

    steps:    steps:

      - name: Checkout      - name: Checkout

        uses: actions/checkout@v4        uses: actions/checkout@v4

            

      - name: Setup Node      - name: Setup Node

        uses: actions/setup-node@v4        uses: actions/setup-node@v4

        with:        with:

          node-version: '20'          node-version: '20'

          cache: 'npm'          cache: 'npm'

            

      - name: Install dependencies      - name: Install dependencies

        run: npm install        run: npm install

            

      - name: Build      - name: Build

        run: npm run build        run: npm run build

            

      - name: Upload artifact      - name: Upload artifact

        uses: actions/upload-pages-artifact@v3        uses: actions/upload-pages-artifact@v3

        with:        with:

          path: 'dist'          path: 'dist'

    

  deploy:  deploy:

    environment:    environment:

      name: github-pages      name: github-pages

      url: ${{ steps.deployment.outputs.page_url }}      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest    runs-on: ubuntu-latest

    needs: build    needs: build

    steps:    steps:

      - name: Deploy to GitHub Pages      - name: Deploy to GitHub Pages

        id: deployment        id: deployment

        uses: actions/deploy-pages@v4        uses: actions/deploy-pages@v4
